"""Cross-language golden-vector test for ``flrng.SplitMix64`` + ``derive``.

The canonical fixture is generated by ``harness/tools/generate_golden.py`` and
lives at ``simulator/src/test/resources/fl/splitmix64_golden.csv``. The same
file is read by ``SplitMix64GoldenTest.java``. Any drift on either side
breaks CI on both — that is the contract.

For each of the 20 ``(seed, round, node)`` triples we assert:

* the first three ``next_long()`` draws from a fresh derived stream match the
  recorded 64-bit bit patterns;
* the first three ``next_double()`` draws match the recorded IEEE-754 bit
  patterns (bitwise compared via ``struct``, not float-equality);
* the first ``next_int(7)`` draw matches the recorded value — locking the
  rejection-sampling agreement with the Java mirror.
"""
from __future__ import annotations

import csv
import struct
from pathlib import Path

import pytest

from flrng import SplitMix64, derive

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
GOLDEN_CSV = (
    PROJECT_ROOT
    / "simulator"
    / "src"
    / "test"
    / "resources"
    / "fl"
    / "splitmix64_golden.csv"
)


def _parse_hex(s: str) -> int:
    return int(s.strip(), 16)


def _load_rows():
    if not GOLDEN_CSV.exists():
        raise FileNotFoundError(
            f"Golden CSV not found at {GOLDEN_CSV}. "
            "Regenerate with: py harness/tools/generate_golden.py"
        )
    rows = []
    with open(GOLDEN_CSV, "r", encoding="utf-8") as f:
        # Skip the '#'-prefixed banner lines, then read as CSV with headers.
        cleaned = [ln for ln in f if not ln.startswith("#")]
    reader = csv.DictReader(cleaned)
    for r in reader:
        rows.append(
            {
                "seed": _parse_hex(r["seed_hex"]),
                "round": int(r["round"]),
                "node": int(r["node"]),
                "longs": [
                    _parse_hex(r["long0_hex"]),
                    _parse_hex(r["long1_hex"]),
                    _parse_hex(r["long2_hex"]),
                ],
                "double_bits": [
                    _parse_hex(r["double0_bits"]),
                    _parse_hex(r["double1_bits"]),
                    _parse_hex(r["double2_bits"]),
                ],
                "nextint7": int(r["nextint7"]),
            }
        )
    return rows


def _double_bits(x: float) -> int:
    (bits,) = struct.unpack(">Q", struct.pack(">d", x))
    return bits


def test_golden_vectors_present():
    rows = _load_rows()
    assert len(rows) == 20, (
        f"expected exactly 20 golden vectors, got {len(rows)} -- "
        "regenerate via py harness/tools/generate_golden.py if the table changed"
    )


@pytest.mark.parametrize("row_index", range(20))
def test_golden_vectors(row_index):
    rows = _load_rows()
    row = rows[row_index]

    # --- next_long ---
    rng = derive(row["seed"], row["round"], row["node"])
    for j in range(3):
        got = rng.next_long()
        want = row["longs"][j]
        assert got == want, (
            f"row {row_index} (seed=0x{row['seed']:016X} round={row['round']} "
            f"node={row['node']}): next_long[{j}] mismatch -- "
            f"expected 0x{want:016X} got 0x{got:016X}"
        )

    # --- next_double (fresh derive) ---
    rng_d = derive(row["seed"], row["round"], row["node"])
    for j in range(3):
        got = rng_d.next_double()
        got_bits = _double_bits(got)
        want_bits = row["double_bits"][j]
        assert got_bits == want_bits, (
            f"row {row_index} (seed=0x{row['seed']:016X} round={row['round']} "
            f"node={row['node']}): next_double[{j}] bits mismatch -- "
            f"expected 0x{want_bits:016X} got 0x{got_bits:016X}"
        )

    # --- next_int(7) (fresh derive) ---
    rng_i = derive(row["seed"], row["round"], row["node"])
    got_int = rng_i.next_int(7)
    assert got_int == row["nextint7"], (
        f"row {row_index} (seed=0x{row['seed']:016X} round={row['round']} "
        f"node={row['node']}): next_int(7) mismatch -- "
        f"expected {row['nextint7']} got {got_int}"
    )


def test_next_int_rejects_non_positive_bound():
    rng = SplitMix64(0)
    with pytest.raises(ValueError):
        rng.next_int(0)
    with pytest.raises(ValueError):
        rng.next_int(-3)


def test_derive_sameness_and_independence():
    a = derive(42, 0, 0)
    b = derive(42, 0, 0)
    for _ in range(32):
        assert a.next_long() == b.next_long(), "same key should reproduce stream"

    a_fresh = derive(42, 0, 0)
    c = derive(42, 0, 1)
    d = derive(42, 1, 0)
    a0 = a_fresh.next_long()
    c0 = c.next_long()
    d0 = d.next_long()
    assert a0 != c0, "different node should diverge on first draw"
    assert a0 != d0, "different round should diverge on first draw"


def test_next_double_is_in_unit_interval():
    rng = derive(2026, 7, 13)
    for _ in range(10_000):
        x = rng.next_double()
        assert 0.0 <= x < 1.0, f"next_double yielded {x!r} outside [0,1)"


def test_next_int_distribution_smoke():
    """Smoke check that next_int(7) hits every bucket over a small sample.

    This is not a statistical test (rejection sampling is exact by
    construction); it just guards against an off-by-one bug that would
    silently exclude bucket 0 or 6.
    """
    rng = derive(2026, 0, 0)
    counts = [0] * 7
    for _ in range(7_000):
        counts[rng.next_int(7)] += 1
    assert all(c > 0 for c in counts), f"some buckets empty: {counts}"
