
package hu.u_szeged.inf.fog.simulator.iot.strategy;

import hu.u_szeged.inf.fog.simulator.application.Application;
import hu.u_szeged.inf.fog.simulator.iot.mobility.MobilityEvent;
import java.util.ArrayList;

/**
 * This class represents a device strategy for finding an application based
 * on the physical distance and the type of tasks the application can process.
 */
public class DistanceAndTypeBasedDeviceStrategy extends DeviceStrategy {

    /**
     * If there are available applications that are capacble of processing the
     * Task Type generated by the device, then the closest one will be chosen.
     * As it can cause a node change, the latency must be updated.
     */
    @Override
    public void findApplication() {
        this.chosenApplication = null;
        ArrayList<Application> availableApplications = this.getAvailableApplications();

        if (!availableApplications.isEmpty()) {
            double min = Double.MAX_VALUE;
            this.chosenApplication = null;
            for (Application app : availableApplications) {
                if (app.types.contains(this.device.type)){
                    if (this.device.geoLocation.calculateDistance(app.computingAppliance.geoLocation) < min) {
                        min = this.device.geoLocation.calculateDistance(app.computingAppliance.geoLocation);
                        this.chosenApplication = app;
                    }
                }
            }
        }

        MobilityEvent.refresh(this.device, this.chosenApplication);
    }
}