
package hu.u_szeged.inf.fog.simulator.iot.strategy;

import hu.mta.sztaki.lpds.cloud.simulator.io.StorageObject;
import hu.mta.sztaki.lpds.cloud.simulator.io.VirtualAppliance;
import hu.u_szeged.inf.fog.simulator.application.Application;
import hu.u_szeged.inf.fog.simulator.iot.TaskType;
import hu.u_szeged.inf.fog.simulator.iot.mobility.MobilityEvent;
import java.util.ArrayList;

/**
 * This class represents a device strategy for finding an application based
 * on the physical distance and the type of tasks the application can process.
 */
public class DistanceAndTypeBasedDeviceStrategy extends DeviceStrategy {

    /**
     * If there are available applications that are capacble of processing the
     * Task Type generated by the device, then the closest one will be chosen.
     * As it can cause a node change, the latency must be updated.
     */
    @Override
    public void findApplication() {
        this.chosenApplication = null;
        ArrayList<Application> availableApplications = this.getAvailableApplications();

        if (!availableApplications.isEmpty()) {
            double min = Double.MAX_VALUE;

            for (Application app : availableApplications) {
                if (app.types.contains(this.device.type)){
                    boolean hasAtleastone = false;
                    for(String commProt : this.device.usableCommunicationProtocols){
                        if(app.computingAppliance.communicationProtocols.contains(commProt)){
                            hasAtleastone = true;
                            break;
                        }
                    }

                    // nem fogunk offloadolni, ha nem tudja feldolgozni a csomópont a tasktypeunk
                    // ha az appban kétszer annyi task van mint futóVM
                    // vagy ha 80% felett van a telefon
                    if (!hasAtleastone || app.tasks.size() > app.countRunningVms() * 2 ||
                            (this.device.battery != null && this.device.battery.getCurrentPercentage() > 80)){
                        continue;
                    }

                    if (this.device.geoLocation.calculateDistance(app.computingAppliance.geoLocation) < min) {
                        min = this.device.geoLocation.calculateDistance(app.computingAppliance.geoLocation);
                        this.chosenApplication = app;
                    }
                }
            }
        }

        MobilityEvent.refresh(this.device, this.chosenApplication);
    }
}