package hu.u_szeged.inf.fog.simulator.fl.cosim;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import hu.u_szeged.inf.fog.simulator.fl.topology.FLTopology;
import hu.u_szeged.inf.fog.simulator.fl.topology.Lambda2;
import hu.u_szeged.inf.fog.simulator.fl.topology.TopologyFactory;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * P1.5 DoD: the Pass-1 {@code system_trace.json} round-trips through the writer
 * and reader, and the deterministic serialisation matches the committed sample
 * fixture that the Python loader ({@code test_system_trace_loader.py}) reads —
 * proving the cross-language round-trip without a run-ordering dependency.
 *
 * <p>The fixture is regenerated by running this test with
 * {@code -Dregen.fixtures=true} (mirrors {@code harness/tools/generate_golden.py}
 * for the RNG vectors). Comparison strips {@code \r} so a CRLF checkout cannot
 * spuriously fail it.</p>
 */
class SystemTraceRoundTripTest {

    private static final String FIXTURE_RESOURCE = "/fl/sample_system_trace.json";
    private static final Path FIXTURE_SOURCE_PATH =
            Paths.get("src", "test", "resources", "fl", "sample_system_trace.json");

    private static final long SEED = 42L;
    private static final double P_LINK = 0.9;
    private static final int ROUNDS = 3;

    /**
     * The canonical sample trace: the §9 two-cluster base graph (2×3, 2
     * bridges) made dynamic, with a 3-round inactive schedule, λ̄₂ / union-λ₂
     * metadata, node descriptors, load profiles, hyper and model blocks — so
     * every schema field (including the nullable dynamic ones) is exercised.
     */
    private static SystemTrace buildSample() {
        FLTopology base = TopologyFactory.clustered(new int[] { 3, 3 }, 2);

        // Dynamic metadata (each call restores all-active before returning).
        List<SystemTrace.DynamicRoundJson> schedule =
                SystemTraceWriter.buildDynamicSchedule(base, SEED, P_LINK, ROUNDS);
        double barLambda = Lambda2.expectedLambda2(base, P_LINK, ROUNDS, SEED);
        double unionLambda = Lambda2.unionLambda2(base, P_LINK, ROUNDS, SEED);

        // Node descriptors (cluster A near-edge, cluster B far-edge), arbitrary
        // but fixed values so the fixture is deterministic.
        List<SystemTrace.NodeJson> nodes = new ArrayList<>();
        String[] profiles = { "near_A1", "near_A2", "near_A3", "far_B1", "far_B2", "far_B3" };
        int[] cores = { 6, 8, 12, 4, 4, 4 };
        double[] mips = { 0.003, 0.004, 0.006, 0.001, 0.001, 0.0012 };
        double[] ram = { 8, 16, 16, 8, 4, 8 };
        int[] cluster = base.clusterLabels();
        for (int i = 0; i < base.size(); i++) {
            SystemTrace.GeoJson geo = new SystemTrace.GeoJson(47.0 + i * 0.1, 19.0 + i * 0.1);
            nodes.add(new SystemTrace.NodeJson(i, profiles[i], cores[i], mips[i], ram[i], geo, cluster[i]));
        }

        SystemTrace.Hyper hyper = new SystemTrace.Hyper();
        hyper.k = 2;
        hyper.rounds = 100;
        hyper.localEpochs = 1;
        hyper.gammaSchedule = "EXPLORE_THEN_EXPLOIT";
        hyper.mergeRule = "DRIFT_SUPPRESSED";
        hyper.policy = "COMPOSITE";
        hyper.dirichletRho = 0.5;
        hyper.signatureDim = 256;
        hyper.signatureSeed = 1234L;

        SystemTrace.Model model = new SystemTrace.Model();
        model.name = "cifar10_cnn_v1";
        model.paramCount = 1_000_000L;
        model.payloadBytesFloat32 = 4_000_000L;

        Map<String, double[]> load = new LinkedHashMap<>();
        load.put("0", new double[] { 0.31, 0.28, 0.30 });
        load.put("1", new double[] { 0.10, 0.12, 0.11 });

        Map<String, Object> params = new LinkedHashMap<>();
        params.put("base", "clustered_2x3");
        params.put("bridges", 2);
        params.put("p_link", P_LINK);

        return SystemTraceWriter.build("S_sample_dynamic", SEED, base, "dynamic", params,
                nodes, hyper, model, load, barLambda, unionLambda, schedule);
    }

    @Test
    @DisplayName("write → read round-trips all fields in memory")
    void roundTripInMemory(@TempDir Path tmp) throws IOException {
        SystemTrace original = buildSample();
        Path out = tmp.resolve("system_trace.json");
        SystemTraceWriter.write(out, original);
        assertTrue(Files.exists(out));

        SystemTrace back = SystemTraceWriter.read(out);
        assertEquals(original.schemaVersion, back.schemaVersion);
        assertEquals(original.scenarioId, back.scenarioId);
        assertEquals(original.seed, back.seed);
        assertEquals(original.n, back.n);
        assertEquals(original.topology.type, back.topology.type);
        assertEquals(original.topology.hash, back.topology.hash);
        assertEquals(original.topology.edges.size(), back.topology.edges.size());
        assertEquals(original.topology.nodes.size(), back.topology.nodes.size());
        assertEquals(original.topology.lambda2, back.topology.lambda2, 1e-12);
        assertEquals(original.topology.lambda2Expected, back.topology.lambda2Expected, 1e-12);
        assertEquals(original.topology.lambda2Union, back.topology.lambda2Union, 1e-12);
        assertEquals(original.topology.dynamicSchedule.size(), back.topology.dynamicSchedule.size());
        // Spot-check edge fidelity.
        for (int i = 0; i < original.topology.edges.size(); i++) {
            SystemTrace.EdgeJson a = original.topology.edges.get(i);
            SystemTrace.EdgeJson b = back.topology.edges.get(i);
            assertEquals(a.u, b.u);
            assertEquals(a.v, b.v);
            assertEquals(a.latencyTicks, b.latencyTicks);
            assertEquals(a.bandwidthBytesPerTick, b.bandwidthBytesPerTick);
        }
        // Hyper / model round-trip.
        assertEquals(original.hyper.signatureDim, back.hyper.signatureDim);
        assertEquals(original.model.payloadBytesFloat32, back.model.payloadBytesFloat32);
        // Load profiles.
        assertArrayEquals(original.loadProfiles.get("0"), back.loadProfiles.get("0"), 1e-12);
    }

    @Test
    @DisplayName("deterministic serialisation matches the committed Python fixture")
    void fixtureMatchesFreshOutput() throws IOException {
        SystemTrace sample = buildSample();
        String fresh = SystemTraceWriter.toJson(sample);

        if (Boolean.getBoolean("regen.fixtures")) {
            Files.createDirectories(FIXTURE_SOURCE_PATH.getParent());
            Files.write(FIXTURE_SOURCE_PATH, (fresh + "\n").getBytes(StandardCharsets.UTF_8));
            System.out.println("[regen] wrote " + FIXTURE_SOURCE_PATH.toAbsolutePath());
            return;
        }

        String committed = readResource(FIXTURE_RESOURCE);
        assertNotNull(committed,
                "fixture " + FIXTURE_RESOURCE + " missing — regenerate with -Dregen.fixtures=true");
        assertEquals(normalise(committed), normalise(fresh),
                "serialised system_trace.json drifted from the committed fixture; "
                        + "regenerate with -Dregen.fixtures=true and re-run the Python loader test");
    }

    private static String normalise(String s) {
        return s.replace("\r", "").trim();
    }

    private static String readResource(String resource) throws IOException {
        InputStream in = SystemTraceRoundTripTest.class.getResourceAsStream(resource);
        if (in == null) {
            return null;
        }
        try (BufferedReader r = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8))) {
            return r.lines().collect(Collectors.joining("\n"));
        }
    }
}
