package hu.u_szeged.inf.fog.simulator.util;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Cross-language golden-vector test for {@link SplitMix64} + {@link
 * SimRandom#derive(long, int, int)}. The canonical fixture is generated by
 * {@code harness/tools/generate_golden.py} and lives at
 * {@code simulator/src/test/resources/fl/splitmix64_golden.csv}; the same
 * file is read by {@code harness/tests/test_flrng_golden.py}. Any drift on
 * either side breaks CI on both.
 *
 * <p>For each of the 20 {@code (seed, round, node)} triples we assert:</p>
 * <ul>
 *   <li>the first three {@code nextLong()} draws from a fresh derived stream
 *       match the recorded 64-bit bit patterns;</li>
 *   <li>the first three {@code nextDouble()} draws from a fresh derived stream
 *       match the recorded IEEE-754 bit patterns (bitwise compared via
 *       {@link Double#doubleToLongBits(double)}, not float-equality);</li>
 *   <li>the first {@code nextInt(7)} draw from a fresh derived stream matches
 *       the recorded value — locking the rejection-sampling agreement with
 *       Python.</li>
 * </ul>
 */
class SplitMix64GoldenTest {

    private static final String GOLDEN_RESOURCE = "/fl/splitmix64_golden.csv";

    /** One row of the golden CSV. */
    private static final class GoldenRow {
        final long seed;
        final int round;
        final int node;
        final long[] longs;       // 3 values, raw 64-bit patterns
        final long[] doubleBits;  // 3 values, IEEE-754 64-bit patterns
        final int nextInt7;       // single value

        GoldenRow(long seed, int round, int node, long[] longs, long[] doubleBits, int nextInt7) {
            this.seed = seed;
            this.round = round;
            this.node = node;
            this.longs = longs;
            this.doubleBits = doubleBits;
            this.nextInt7 = nextInt7;
        }
    }

    private static long parseHex64(String s) {
        // Accept "0x..." and tolerate leading/trailing whitespace.
        String trimmed = s.trim();
        if (trimmed.startsWith("0x") || trimmed.startsWith("0X")) {
            trimmed = trimmed.substring(2);
        }
        // The value is an unsigned 64-bit pattern; Long.parseLong(., 16) rejects
        // the top bit, so use Long.parseUnsignedLong.
        return Long.parseUnsignedLong(trimmed, 16);
    }

    private static List<GoldenRow> loadGolden() throws IOException {
        InputStream in = SplitMix64GoldenTest.class.getResourceAsStream(GOLDEN_RESOURCE);
        assertNotNull(in, "Golden resource " + GOLDEN_RESOURCE + " not found on the classpath. "
                + "Regenerate with: py harness/tools/generate_golden.py");

        List<GoldenRow> rows = new ArrayList<>();
        try (BufferedReader r = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8))) {
            String line;
            boolean headerSeen = false;
            while ((line = r.readLine()) != null) {
                if (line.isEmpty() || line.startsWith("#")) continue;
                if (!headerSeen) {
                    headerSeen = true;
                    continue; // skip the CSV header line
                }
                String[] f = line.split(",");
                if (f.length != 10) {
                    throw new IOException("Bad golden row (expected 10 fields): " + line);
                }
                long seed = parseHex64(f[0]);
                int round = Integer.parseInt(f[1].trim());
                int node = Integer.parseInt(f[2].trim());
                long[] longs = { parseHex64(f[3]), parseHex64(f[4]), parseHex64(f[5]) };
                long[] dbs = { parseHex64(f[6]), parseHex64(f[7]), parseHex64(f[8]) };
                int ni7 = Integer.parseInt(f[9].trim());
                rows.add(new GoldenRow(seed, round, node, longs, dbs, ni7));
            }
        }
        return rows;
    }

    @Test
    @DisplayName("derive(seed, round, node) reproduces 20 recorded golden vectors bit-for-bit")
    void goldenVectors() throws IOException {
        List<GoldenRow> rows = loadGolden();
        assertEquals(20, rows.size(),
                "expected exactly 20 golden vectors (regenerate via "
                + "harness/tools/generate_golden.py if the table has changed)");

        for (int i = 0; i < rows.size(); i++) {
            GoldenRow row = rows.get(i);

            // --- next_long stream ---
            SplitMix64 rng = SimRandom.derive(row.seed, row.round, row.node);
            for (int j = 0; j < 3; j++) {
                long got = rng.nextLong();
                assertEquals(row.longs[j], got,
                        () -> String.format(
                                "row %d (seed=0x%016X round=%d node=%d): nextLong[%d] mismatch -- "
                                        + "expected 0x%016X got 0x%016X",
                                rows.indexOf(row), row.seed, row.round, row.node, 0,
                                row.longs[0], got));
            }

            // --- next_double stream (fresh derive) ---
            SplitMix64 rngD = SimRandom.derive(row.seed, row.round, row.node);
            for (int j = 0; j < 3; j++) {
                double got = rngD.nextDouble();
                long gotBits = Double.doubleToLongBits(got);
                final int jj = j;
                assertEquals(row.doubleBits[j], gotBits,
                        () -> String.format(
                                "row %d (seed=0x%016X round=%d node=%d): nextDouble[%d] bits mismatch -- "
                                        + "expected 0x%016X (%a) got 0x%016X (%a)",
                                rows.indexOf(row), row.seed, row.round, row.node, jj,
                                row.doubleBits[jj], Double.longBitsToDouble(row.doubleBits[jj]),
                                gotBits, got));
            }

            // --- next_int(7) (fresh derive) ---
            SplitMix64 rngI = SimRandom.derive(row.seed, row.round, row.node);
            int got = rngI.nextInt(7);
            assertEquals(row.nextInt7, got,
                    "row " + i + " (seed=0x" + Long.toHexString(row.seed).toUpperCase()
                            + " round=" + row.round + " node=" + row.node
                            + "): nextInt(7) mismatch -- expected " + row.nextInt7 + " got " + got);
        }
    }

    @Test
    @DisplayName("nextInt rejects bound <= 0")
    void nextIntRejectsNonPositiveBound() {
        SplitMix64 rng = new SplitMix64(0L);
        assertThrows(IllegalArgumentException.class, () -> rng.nextInt(0));
        assertThrows(IllegalArgumentException.class, () -> rng.nextInt(-3));
    }

    @Test
    @DisplayName("derive: same (seed, round, node) -> identical streams; different node -> divergent")
    void deriveSamenessAndIndependence() {
        SplitMix64 a = SimRandom.derive(42L, 0, 0);
        SplitMix64 b = SimRandom.derive(42L, 0, 0);
        for (int i = 0; i < 32; i++) {
            assertEquals(a.nextLong(), b.nextLong(), "same key should reproduce stream");
        }

        SplitMix64 c = SimRandom.derive(42L, 0, 1);
        SplitMix64 d = SimRandom.derive(42L, 1, 0);
        // Both streams should disagree with `a` on the very first draw (overwhelmingly likely).
        // Re-derive `a` to compare against draw[0].
        SplitMix64 aFresh = SimRandom.derive(42L, 0, 0);
        long a0 = aFresh.nextLong();
        long c0 = c.nextLong();
        long d0 = d.nextLong();
        // We assert pairwise inequality. A collision is cryptographically negligible.
        if (a0 == c0) {
            throw new AssertionError("derive(seed=42, round=0, node=0) and (..., node=1) should "
                    + "produce different first draws");
        }
        if (a0 == d0) {
            throw new AssertionError("derive(seed=42, round=0, node=0) and (..., round=1, node=0) "
                    + "should produce different first draws");
        }
    }
}
